fastq-dir: /path/to/fastq-directory/
samples-file: /path/to/samples-file.txt
outdir: /path/to/output-directory/


## temporary directory for input and output data, e.g. on the cs
## cluster no temporary directory is used when this is set to False or
## ''
scratchdir: /path/to/scratch-directory/

grep-column: 0
grep-term: ""

paired-end: 1


################################
#
#    refereces and indices
#
################################

## all references and indices have to be in the same directory
reference-dir: /path/to/reference-directory/

## check reference name
fasta: chr19.fa
sequence-index: [chr19.fa.*, chr19.dict]

known-sites: [dbsnp_138.hg38.chr19.vcf.gz, Homo_sapiens_assembly38.known_indels.chr19.vcf.gz, Mills_and_1000G_gold_standard.indels.hg38.chr19.vcf.gz]

known-sites-index: [dbsnp_138.hg38.chr19.vcf.gz.tbi, Homo_sapiens_assembly38.known_indels.chr19.vcf.gz.tbi, Mills_and_1000G_gold_standard.indels.hg38.chr19.vcf.gz.tbi]

## name of file to select regions (-L option in GATK), set to '' if no
## regions are to be selected
## TODO explain where it is used
intervals-file: ''
interval-padding: 0


################################
#
#    mapper options
#
################################

mapper: bwa

mapper-options: "-K 100000000 -Y -t 4 -v 2"


################################
#
#    qsub options
#
################################

## SGE job submission
## sets tmem and h_vmem
mem: 8G
## sets tscratch, reserving this amount of space on the scratch0
## set to low value in case scratch is False
tscratch: 1G
time: "00:30:00"


################################
#
#    environment modules
#
################################

## set to False if modules should not be used
modules: True

module-lib: /share/apps/cto/modulefiles

## NOTE: this path differs on the various systems
## on andrey
## module-init: /usr/share/modules/init/python.py
## on the computer science cluster
module-init: /usr/share/lmod/lmod/init/env_modules_python.py

module-list: python/3.6.1, java/15.0.2, R/4.0.2, bwa/0.7.15, samtools/1.8, fastqc/0.11.4, picard-tools/2.21.8, sambamba/0.5.9, samblaster/0.1.24, gatk/4.1.4.1
