vcf-dir: /path/to/vcf-directory/
cohorts-file: /path/to/cohorts-file.txt
outdir: /path/to/output-directory/


## temporary directory for input and output data, e.g. on the cs
## cluster no temporary directory is used when this is set to False or
## ''
scratchdir: /path/to/scratch-directory/

grep-column: 0
grep-term: ""
paired-end: 1


################################
#
#    refereces and indices
#
################################

## all references and indices have to be in the same directory
reference-dir: /path/to/reference-directory/

## check reference name
fasta: chr19.fa

sequence-index: [chr19.fa.fai, chr19.dict]

known-sites: [dbsnp_138.hg38.chr19.vcf.gz, Homo_sapiens_assembly38.known_indels.chr19.vcf.gz, Mills_and_1000G_gold_standard.indels.hg38.chr19.vcf.gz, hapmap_3.3.hg38.chr19.vcf.gz, 1000G_omni2.5.hg38.chr19.vcf.gz, 1000G_phase1.snps.high_confidence.hg38.chr19.vcf.gz, Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.chr19.vcf.gz]

known-sites-index: [dbsnp_138.hg38.chr19.vcf.gz.tbi, Homo_sapiens_assembly38.known_indels.chr19.vcf.gz.tbi, Mills_and_1000G_gold_standard.indels.hg38.chr19.vcf.gz.tbi, hapmap_3.3.hg38.chr19.vcf.gz.tbi, 1000G_omni2.5.hg38.chr19.vcf.gz.tbi, 1000G_phase1.snps.high_confidence.hg38.chr19.vcf.gz.tbi, Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.chr19.vcf.gz.tbi]


## {refdir} is interpolated to the path to the reference directory
snp-resource-string: ' --resource:hapmap,known=false,training=true,truth=true,prior=15.0 {refdir}/hapmap_3.3.hg38.chr19.vcf.gz --resource:omni,known=false,training=true,truth=false,prior=12.0 {refdir}/1000G_omni2.5.hg38.chr19.vcf.gz --resource:1000G,known=false,training=true,truth=false,prior=10.0 {refdir}/1000G_phase1.snps.high_confidence.hg38.chr19.vcf.gz --resource:dbsnp,known=true,training=false,truth=false,prior=2.0 {refdir}/dbsnp_138.hg38.chr19.vcf.gz'

indel-resource-string: ' --resource mills,known=false,training=true,truth=true,prior=12:{refdir}/Mills_and_1000G_gold_standard.indels.hg38.chr19.vcf.gz --resource dbsnp,known=true,training=false,truth=false,prior=2.0:{refdir}/dbsnp_138.hg38.chr19.vcf.gz --resource axiomPoly,known=false,training=true,truth=false,prior=10:{refdir}/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.chr19.vcf.gz'


## list of intervals or name of bed file to select regions (gatk -L
## option), set to '' if no regions are to be selected. caveat:
## GenomicsDBImport requires at least one interval!

intervals-file: chr19.bed
interval-padding: 0

## filter expression for gatk VariantFiltration, set '' for no filtration
filter-string: '--filter-expression "ExcessHet > 54.69" --filter-name ExcessHet'

################################
#
#    qsub options
#
################################

## SGE job submission
## sets tmem and h_vmem, maybe more (48G) when using star
mem: 3G
## sets src, count of the free space on the scratch0 at the point of submission
scr: 10G
## sets tscratch, reserving this amount of space on the scratch0
tscratch: 10G
time: "00:12:00"


################################
#
#    environment modules
#
################################

## set to False if modules should not be used
modules: True

module-lib: /share/apps/cto/modulefiles

## NOTE: this path differs on the various systems
## on ubuntu
module-init: /usr/share/modules/init/python.py
## on centos
## module-init: /usr/share/Modules/init/python.py

module-list: python/2.7.8, gatk/4.1.4.1, R/3.6.1, picard-tools/2.21.8
